# Generated by Django 2.0.1 on 2018-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka_app', '0003_zamowienieklient_zamowienieprodukt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.IntegerField(null=True),
        ),
    ]
