# Generated by Django 2.0.1 on 2018-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka_app', '0004_produkt_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='nazwa_ikony',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='zatwierdzone',
            field=models.BooleanField(default=False),
        ),
    ]
