# Generated by Django 2.0.1 on 2018-01-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka_app', '0005_auto_20180122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='nazwa_ikony',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='adresWysylki',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='sposobWysylki',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='sposobZaplaty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
